os: Visual Studio 2015

platform:
  - x64

configuration: Release

clone_folder: c:\projects\libwebrtc

build:
  project: PACKAGE.vcxproj

before_build:
  - cd c:\projects\libwebrtc
  - git submodule update --init --recursive
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=c:\projects\libwebrtc .

artifacts:
  - path: libwebrtc-0.0.1-rc.4-win32-x64.7z
    name: libwebrtc-0.0.1-rc.4-win32-x64.7z
